import clsx from 'clsx';
import type { Metadata } from 'next';
import { Barlow, Fraunces } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';

const barlow = Barlow({
  subsets: ['latin'],
  weight: '600',
  variable: '--font-barlow',
});
const fraunces = Fraunces({
  subsets: ['latin'],
  weight: ['700', '900'],
  variable: '--font-fraunces',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  const fonts = clsx([barlow.variable, fraunces.variable]);

  return (
    <html lang="en">
      <body className={fonts}>{children}</body>
    </html>
  );
}
